spring:
  application:
    name: balancer

server:
  port: 8888

backside:
  ribbon:
    eureka:
      enabled: false
    listOfServers: 54.233.124.156:8091,15.228.9.62:8090
    ServerListRefreshInterval: 15000
